Repo Hash (Nightly Test):     [c2c1aa5]
Repo Hash (Cloudformation):   [6f4be6f]
Nightly Test in the unity-cm account
Stack Name: [unity-management-console-unity-nightly]
Stack Status (Final): [CREATE_COMPLETE]
Stack Creation Time: [540 seconds] - PASS
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-8.0.2, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/ubuntu/unity-cs-infra/nightly_tests
collecting ... collected 9 items

test_selenium_mc.py::test_navigate_to_mc_console PASSED                  [ 11%]
test_selenium_mc.py::test_bootstrap_process_status PASSED                [ 22%]
test_selenium_mc.py::test_initiate_core_setup PASSED                     [ 33%]
test_selenium_mc.py::test_core_setup_save_btn PASSED                     [ 44%]
test_selenium_mc.py::test_click_install_SPS_btn FAILED                   [ 55%]
test_selenium_mc.py::test_SPS_module_name FAILED                         [ 66%]
test_selenium_mc.py::test_SPS_module_branch FAILED                       [ 77%]
test_selenium_mc.py::test_click_SPS_install_btns FAILED                  [ 88%]
test_selenium_mc.py::test_grab_terminal_output_SPS FAILED                [100%]

=================================== FAILURES ===================================
__________________________ test_click_install_SPS_btn __________________________
test_selenium_mc.py:158: in test_click_install_SPS_btn
    install_button = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x55ef1125c793 <unknown>
E   #1 0x55ef10f501c6 <unknown>
E   #2 0x55ef10f9b358 <unknown>
E   #3 0x55ef10f9b411 <unknown>
E   #4 0x55ef10fde934 <unknown>
E   #5 0x55ef10fbd3fd <unknown>
E   #6 0x55ef10fdbdd9 <unknown>
E   #7 0x55ef10fbd173 <unknown>
E   #8 0x55ef10f8e2d3 <unknown>
E   #9 0x55ef10f8ec9e <unknown>
E   #10 0x55ef112208cb <unknown>
E   #11 0x55ef11224745 <unknown>
E   #12 0x55ef1120d2e1 <unknown>
E   #13 0x55ef112252d2 <unknown>
E   #14 0x55ef111f117f <unknown>
E   #15 0x55ef1124adc8 <unknown>
E   #16 0x55ef1124afc3 <unknown>
E   #17 0x55ef1125b944 <unknown>
E   #18 0x7fe6e43adac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:167: in test_click_install_SPS_btn
    raise Exception("Failed to install EKS - either the button was not clickable or the URL did not update as expected.")
E   Exception: Failed to install EKS - either the button was not clickable or the URL did not update as expected.
_____________________________ test_SPS_module_name _____________________________
test_selenium_mc.py:180: in test_SPS_module_name
    text_box = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x55ef1125c793 <unknown>
E   #1 0x55ef10f501c6 <unknown>
E   #2 0x55ef10f9b358 <unknown>
E   #3 0x55ef10f9b411 <unknown>
E   #4 0x55ef10fde934 <unknown>
E   #5 0x55ef10fbd3fd <unknown>
E   #6 0x55ef10fdbdd9 <unknown>
E   #7 0x55ef10fbd173 <unknown>
E   #8 0x55ef10f8e2d3 <unknown>
E   #9 0x55ef10f8ec9e <unknown>
E   #10 0x55ef112208cb <unknown>
E   #11 0x55ef11224745 <unknown>
E   #12 0x55ef1120d2e1 <unknown>
E   #13 0x55ef112252d2 <unknown>
E   #14 0x55ef111f117f <unknown>
E   #15 0x55ef1124adc8 <unknown>
E   #16 0x55ef1124afc3 <unknown>
E   #17 0x55ef1125b944 <unknown>
E   #18 0x7fe6e43adac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:189: in test_SPS_module_name
    raise Exception(f"Failed to find or interact with the specified element (ID: {element_id}).")
E   Exception: Failed to find or interact with the specified element (ID: name).
____________________________ test_SPS_module_branch ____________________________
test_selenium_mc.py:201: in test_SPS_module_branch
    next_button = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x55ef1125c793 <unknown>
E   #1 0x55ef10f501c6 <unknown>
E   #2 0x55ef10f9b358 <unknown>
E   #3 0x55ef10f9b411 <unknown>
E   #4 0x55ef10fde934 <unknown>
E   #5 0x55ef10fbd3fd <unknown>
E   #6 0x55ef10fdbdd9 <unknown>
E   #7 0x55ef10fbd173 <unknown>
E   #8 0x55ef10f8e2d3 <unknown>
E   #9 0x55ef10f8ec9e <unknown>
E   #10 0x55ef112208cb <unknown>
E   #11 0x55ef11224745 <unknown>
E   #12 0x55ef1120d2e1 <unknown>
E   #13 0x55ef112252d2 <unknown>
E   #14 0x55ef111f117f <unknown>
E   #15 0x55ef1124adc8 <unknown>
E   #16 0x55ef1124afc3 <unknown>
E   #17 0x55ef1125b944 <unknown>
E   #18 0x7fe6e43adac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:214: in test_SPS_module_branch
    raise Exception(f"Textbox for branch name (ID: {element_id}) not found.")
E   Exception: Textbox for branch name (ID: branch) not found.
_________________________ test_click_SPS_install_btns __________________________
test_selenium_mc.py:225: in test_click_SPS_install_btns
    next_button = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x55ef1125c793 <unknown>
E   #1 0x55ef10f501c6 <unknown>
E   #2 0x55ef10f9b358 <unknown>
E   #3 0x55ef10f9b411 <unknown>
E   #4 0x55ef10fde934 <unknown>
E   #5 0x55ef10fbd3fd <unknown>
E   #6 0x55ef10fdbdd9 <unknown>
E   #7 0x55ef10fbd173 <unknown>
E   #8 0x55ef10f8e2d3 <unknown>
E   #9 0x55ef10f8ec9e <unknown>
E   #10 0x55ef112208cb <unknown>
E   #11 0x55ef11224745 <unknown>
E   #12 0x55ef1120d2e1 <unknown>
E   #13 0x55ef112252d2 <unknown>
E   #14 0x55ef111f117f <unknown>
E   #15 0x55ef1124adc8 <unknown>
E   #16 0x55ef1124afc3 <unknown>
E   #17 0x55ef1125b944 <unknown>
E   #18 0x7fe6e43adac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:246: in test_click_SPS_install_btns
    raise Exception(f"Failed to find or click the first button (class: {next_button_class}).")
E   NameError: name 'next_button_class' is not defined
________________________ test_grab_terminal_output_SPS _________________________
test_selenium_mc.py:258: in test_grab_terminal_output_SPS
    terminal_output_element = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x55ef1125c793 <unknown>
E   #1 0x55ef10f501c6 <unknown>
E   #2 0x55ef10f9b358 <unknown>
E   #3 0x55ef10f9b411 <unknown>
E   #4 0x55ef10fde934 <unknown>
E   #5 0x55ef10fbd3fd <unknown>
E   #6 0x55ef10fdbdd9 <unknown>
E   #7 0x55ef10fbd173 <unknown>
E   #8 0x55ef10f8e2d3 <unknown>
E   #9 0x55ef10f8ec9e <unknown>
E   #10 0x55ef112208cb <unknown>
E   #11 0x55ef11224745 <unknown>
E   #12 0x55ef1120d2e1 <unknown>
E   #13 0x55ef112252d2 <unknown>
E   #14 0x55ef111f117f <unknown>
E   #15 0x55ef1124adc8 <unknown>
E   #16 0x55ef1124afc3 <unknown>
E   #17 0x55ef1125b944 <unknown>
E   #18 0x7fe6e43adac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:262: in test_grab_terminal_output_SPS
    raise Exception("Failed to find or load the terminal output element within the specified time.")
E   Exception: Failed to find or load the terminal output element within the specified time.
=========================== short test summary info ============================
FAILED test_selenium_mc.py::test_click_install_SPS_btn - Exception: Failed to...
FAILED test_selenium_mc.py::test_SPS_module_name - Exception: Failed to find ...
FAILED test_selenium_mc.py::test_SPS_module_branch - Exception: Textbox for b...
FAILED test_selenium_mc.py::test_click_SPS_install_btns - NameError: name 'ne...
FAILED test_selenium_mc.py::test_grab_terminal_output_SPS - Exception: Failed...
=================== 5 failed, 4 passed in 135.08s (0:02:15) ====================
